spring:
  profiles:
    active: local
    
  datasource:
    url: jdbc:mariadb://localhost:3306/timblo
    username: root
    password: timbel
    driver-class-name: org.mariadb.jdbc.Driver
    
    
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 30MB

server:
  port: 8080
  servlet:
    context-path: /
    
# Swagger/OpenAPI 설정
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
    doc-expansion: none
    disable-swagger-default-url: true
    display-request-duration: true
  packages-to-scan: egovframework.liveapi
  paths-to-match: /api/live/**
    
gateway:
  ip: 222.99.52.79
  port: 31981

ssl:
  enabled: false

file:
  path: /data/sales_data